### ISSUE TITLE
工程打开有错误

### ISSUE THREAD

**Issue by Serpit** [kevin-zhan/DailyZhihu#1]
你好，您的工程我clone下来以后，打开发现model.dart的文件有如下错误：
The method '_$StoryModelToJson' isn't defined for the class 'StoryModel'.

Target of URI hasn't been generated: 'model.g.dart'.

请问怎么解决

**Comment by kevin-zhan** [comment]
这里是用了[json_serializable](https://pub.dartlang.org/packages/json_serializable)来做json对象的映射，可以了解一下这个库的用法。
这里只需要在根目录下用命令行执行：`flutter packages pub run build_runner watch`，生成model.g.dart文件就可以了。
