### ISSUE TITLE
viewmodel 里面的 depose() 函数调用时机是什么时候

### ISSUE THREAD

**Issue by Echo-Joker** [kevin-zhan/DailyZhihu#3]
depose() {
    _storyListController.close();
  }

**Comment by kevin-zhan** [comment]
感谢关注。很久没维护这个项目了。

这里应该是当时留的坑。

已经在新的提交里fix这个问题了: [fix dispose调用问题](https://github.com/kevin-zhan/DailyZhihu/commit/63345f9399ac8a498dc4141f50a773992e349fc6)
